CREATE DATABASE HotelManagement;
USE HotelManagement;

CREATE TABLE Colors
(
Id INT PRIMARY KEY IDENTITY,
Color VARCHAR(6) NOT NULL UNIQUE
);

CREATE TABLE AccountTypes
(
Id INT PRIMARY KEY IDENTITY,
[Type] VARCHAR(100) UNIQUE
);

CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY,
ColorId INT FOREIGN KEY REFERENCES Colors(Id) NOT NULL,
AccountTypeId INT FOREIGN KEY REFERENCES AccountTypes(Id) NOT NULL,
Email VARCHAR(320) NOT NULL UNIQUE,
[Password] VARCHAR(300) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
);

CREATE TABLE Currencies
(
Id INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(300) NOT NULL,
FormattingString VARCHAR(300) NOT NULL
);

CREATE TABLE Hotels
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULL,
CurrencyId INT FOREIGN KEY REFERENCES Currencies(Id) NOT NULL,
DownPaymentPercentage INT NOT NULL,
[OwnerId] INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE HotelCodeStatuses
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Status] VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE HotelCodes
(
Code VARCHAR(200) PRIMARY KEY NOT NULL,
HotelId INT FOREIGN KEY REFERENCES Hotels(Id) NOT NULL,
UserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
StatusId INT FOREIGN KEY REFERENCES HotelCodeStatuses(Id) NOT NULL,
SenderId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
);

CREATE TABLE UsersHotels
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
UserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
HotelId INT FOREIGN KEY REFERENCES Hotels(Id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE Rooms
(
Id INT PRIMARY KEY IDENTITY,
RoomNumber VARCHAR(50) NOT NULL,
PricePerNight MONEY NOT NULL,
Notes VARCHAR(300),
HotelId INT FOREIGN KEY REFERENCES Hotels(Id) ON DELETE CASCADE NOT NULL 
);

CREATE TABLE Beds
(
Id INT PRIMARY KEY IDENTITY,
BedType VARCHAR(200) NOT NULL,
Capacity INT NOT NULL
);

CREATE TABLE RoomsBeds
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
RoomId INT FOREIGN KEY REFERENCES Rooms(Id) ON DELETE CASCADE NOT NULL,
BedId INT FOREIGN KEY REFERENCES Beds(Id) NOT NULL
);

CREATE TABLE Bookings
(
Id INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL,
DownPaymentPaid BIT NOT NULL,
FullPaymentPaid BIT NOT NULL,
DownPaymentPrice Money NOT NULL,
FullPaymentPrice Money NOT NULL,
Notes VARCHAR(300),
RoomId INT FOREIGN KEY REFERENCES Rooms(Id) ON DELETE CASCADE NOT NULL
);

INSERT INTO Currencies([Name], FormattingString) VALUES
('Leva', '*.lv'),
('Euro', '€*')

INSERT INTO AccountTypes([Type]) VALUES
('Owner'),
('Employee')

INSERT INTO Colors([Color]) VALUES
('ffb3ba'),
('ffdfba'),
('ffffba'),
('baffc9'),
('bae1ff'),
('b4a7d6')

INSERT INTO Beds(BedType, Capacity) VALUES
('Single', 1),
('Twin', 2),
('Triple', 3),
('Single couch', 1),
('Double couch', 2)

INSERT INTO HotelCodeStatuses([Status]) VALUES
('Pending'),
('Accepted'),
('Rejected')